---
- hosts: all
  become: yes
  tasks: 
  - name: ubuntu tree software
    apt:
     name: tree  
     state: present
 
  - name: amazon tree software
    yum:
     name: tree    
     state: present
    