---
- hosts: all
  become: yes
  tasks: 
  - name: ubuntu tree software
    apt:
     name: tree  
     state: present
    when: ansible_os_family =="Debian"
  - name: amazon tree software
    yum: 
     name: tree    
     state: present
    when: ansible_os_family =="RedHat"
      