---
- hosts: webserver
  become: yes
  tasks:
  - name: installing apache2 server on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"

  - name: starting apache2 server on ubuntu
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"  

  - name: installing httpd on amazon
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat" 

  - name: starting httpd on amazon
    yum:
      name: httpd
      state: started
    when: ansible_os_family =="RedHat"     
    ignore_errors: yes