---
- hosts: webserver
  become: yes
  tasks:
  - name: installing apache2 on ubuntu node
    apt: 
      name: apache2
      state: present
    when: ansible_os_family =="Debian"
  
  - nane: starting  apache2 server
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"    

  - name: installing httpd on amazon node
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"  
 
  - nane: starting httpd server
    service:
      name: httpd
      state: started
    when: ansible_os_family =="RedHat" 