---
# tasks file for tomcatroll
- name: install tomcat7
  apt:
    name: tomcat7
    state: present

- name: copy tom config file into nodes
  template:
    src: templates/config.j2
    dest: /etc/default/tomcat7
  notify: restarttomcat

- name: Installing Additional Packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - tomcat7-docs
    - tomcat7-admin
    - tomcat7-examples

- name: copy tom user file into nodes
  template:
    src: templates/user.j2
    dest: /etc/tomcat7/tomcat-users.xml
  notify: restarttomcat
